// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	ErrorCodeContentTooLarge    ErrorCode = "content_too_large"
	ErrorCodeExpired            ErrorCode = "expired"
	ErrorCodeInternalError      ErrorCode = "internal_error"
	ErrorCodeInvalidRequest     ErrorCode = "invalid_request"
	ErrorCodeNotFound           ErrorCode = "not_found"
	ErrorCodeRevoked            ErrorCode = "revoked"
	ErrorCodeServiceUnavailable ErrorCode = "service_unavailable"
	ErrorCodeUnauthorized       ErrorCode = "unauthorized"
	ErrorCodeViewLimitExhausted ErrorCode = "view_limit_exhausted"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeContentTooLarge:
		return true
	case ErrorCodeExpired:
		return true
	case ErrorCodeInternalError:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRevoked:
		return true
	case ErrorCodeServiceUnavailable:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeViewLimitExhausted:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// CreateShareRequest defines model for CreateShareRequest.
type CreateShareRequest struct {
	// Content Markdown limited by MORSEL_MAX_DOCUMENT_BYTES, measured in UTF-8 bytes.
	Content   string           `json:"content"`
	ExpiresIn *int64           `json:"expires_in,omitempty"`
	MaxViews  *int64           `json:"max_views,omitempty"`
	Preview   *PreviewMetadata `json:"preview,omitempty"`
}

// CreateShareResponse defines model for CreateShareResponse.
type CreateShareResponse struct {
	CreatedAt time.Time          `json:"created_at"`
	ExpiresAt *time.Time         `json:"expires_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	MaxViews  *int64             `json:"max_views,omitempty"`
	Preview   *PreviewMetadata   `json:"preview,omitempty"`
	ShareUrl  string             `json:"share_url"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// PreviewMetadata defines model for PreviewMetadata.
type PreviewMetadata struct {
	// Description Plain-text Open Graph description; surrounding whitespace is trimmed and control or line-separator characters are rejected.
	Description string `json:"description"`

	// Title Plain-text Open Graph title; surrounding whitespace is trimmed and control or line-separator characters are rejected.
	Title string `json:"title"`
}

// Share defines model for Share.
type Share struct {
	Content        string     `json:"content"`
	CreatedAt      time.Time  `json:"created_at"`
	ExpiresAt      *time.Time `json:"expires_at,omitempty"`
	MaxViews       *int64     `json:"max_views,omitempty"`
	ViewCount      int64      `json:"view_count"`
	ViewsRemaining *int64     `json:"views_remaining,omitempty"`
}

// ShareCapability defines model for ShareCapability.
type ShareCapability = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// ContentTooLarge defines model for ContentTooLarge.
type ContentTooLarge = Error

// Gone defines model for Gone.
type Gone = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateShareJSONRequestBody defines body for CreateShare for application/json ContentType.
type CreateShareJSONRequestBody = CreateShareRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Report process liveness
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetReadiness Report PostgreSQL readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
	// CreateShare Create a Markdown share
	// (POST /v1/shares)
	CreateShare(w http.ResponseWriter, r *http.Request)
	// RevokeShare Idempotently revoke a share
	// (DELETE /v1/shares/{share})
	RevokeShare(w http.ResponseWriter, r *http.Request, share openapi_types.UUID)
	// ConsumeShare Atomically consume one view and retrieve a share
	// (GET /v1/shares/{share})
	ConsumeShare(w http.ResponseWriter, r *http.Request, share ShareCapability)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetHealth Report process liveness
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Report PostgreSQL readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateShare Create a Markdown share
// (POST /v1/shares)
func (_ Unimplemented) CreateShare(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RevokeShare Idempotently revoke a share
// (DELETE /v1/shares/{share})
func (_ Unimplemented) RevokeShare(w http.ResponseWriter, r *http.Request, share openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ConsumeShare Atomically consume one view and retrieve a share
// (GET /v1/shares/{share})
func (_ Unimplemented) ConsumeShare(w http.ResponseWriter, r *http.Request, share ShareCapability) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShare operation middleware
func (siw *ServerInterfaceWrapper) CreateShare(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShare(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeShare operation middleware
func (siw *ServerInterfaceWrapper) RevokeShare(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "share" -------------
	var share openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "share", chi.URLParam(r, "share"), &share, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "share", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeShare(w, r, share)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConsumeShare operation middleware
func (siw *ServerInterfaceWrapper) ConsumeShare(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "share" -------------
	var share ShareCapability

	err = runtime.BindStyledParameterWithOptions("simple", "share", chi.URLParam(r, "share"), &share, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "share", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConsumeShare(w, r, share)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/shares", wrapper.CreateShare)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/shares/{share}", wrapper.RevokeShare)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/shares/{share}", wrapper.ConsumeShare)
	})

	return r
}

type BadRequestJSONResponse Error

type ContentTooLargeJSONResponse Error

type GoneJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type ServiceUnavailableJSONResponse Error

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate *string
}
type UnauthorizedJSONResponse struct {
	Body Error

	Headers UnauthorizedResponseHeaders
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness200JSONResponse Health

func (response GetReadiness200JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadiness503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetReadiness503JSONResponse) VisitGetReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShareRequestObject struct {
	Body *CreateShareJSONRequestBody
}

type CreateShareResponseObject interface {
	VisitCreateShareResponse(w http.ResponseWriter) error
}

type CreateShare201JSONResponse CreateShareResponse

func (response CreateShare201JSONResponse) VisitCreateShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShare400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateShare400JSONResponse) VisitCreateShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShare401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateShare401JSONResponse) VisitCreateShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShare413JSONResponse struct{ ContentTooLargeJSONResponse }

func (response CreateShare413JSONResponse) VisitCreateShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateShare500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateShare500JSONResponse) VisitCreateShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeShareRequestObject struct {
	Share openapi_types.UUID `json:"share"`
}

type RevokeShareResponseObject interface {
	VisitRevokeShareResponse(w http.ResponseWriter) error
}

type RevokeShare204Response struct {
}

func (response RevokeShare204Response) VisitRevokeShareResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeShare400JSONResponse struct{ BadRequestJSONResponse }

func (response RevokeShare400JSONResponse) VisitRevokeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeShare401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeShare401JSONResponse) VisitRevokeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.WWWAuthenticate != nil {
		w.Header().Set("WWW-Authenticate", fmt.Sprint(*response.Headers.WWWAuthenticate))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeShare404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeShare404JSONResponse) VisitRevokeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeShare500JSONResponse struct{ InternalErrorJSONResponse }

func (response RevokeShare500JSONResponse) VisitRevokeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ConsumeShareRequestObject struct {
	Share ShareCapability `json:"share"`
}

type ConsumeShareResponseObject interface {
	VisitConsumeShareResponse(w http.ResponseWriter) error
}

type ConsumeShare200ResponseHeaders struct {
	CacheControl *string
}

type ConsumeShare200JSONResponse struct {
	Body    Share
	Headers ConsumeShare200ResponseHeaders
}

func (response ConsumeShare200JSONResponse) VisitConsumeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConsumeShare400JSONResponse struct{ BadRequestJSONResponse }

func (response ConsumeShare400JSONResponse) VisitConsumeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ConsumeShare404JSONResponse struct{ NotFoundJSONResponse }

func (response ConsumeShare404JSONResponse) VisitConsumeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ConsumeShare410JSONResponse struct{ GoneJSONResponse }

func (response ConsumeShare410JSONResponse) VisitConsumeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(410)
	_, err := buf.WriteTo(w)
	return err
}

type ConsumeShare500JSONResponse struct{ InternalErrorJSONResponse }

func (response ConsumeShare500JSONResponse) VisitConsumeShareResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Report process liveness
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetReadiness Report PostgreSQL readiness
	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)
	// CreateShare Create a Markdown share
	// (POST /v1/shares)
	CreateShare(ctx context.Context, request CreateShareRequestObject) (CreateShareResponseObject, error)
	// RevokeShare Idempotently revoke a share
	// (DELETE /v1/shares/{share})
	RevokeShare(ctx context.Context, request RevokeShareRequestObject) (RevokeShareResponseObject, error)
	// ConsumeShare Atomically consume one view and retrieve a share
	// (GET /v1/shares/{share})
	ConsumeShare(ctx context.Context, request ConsumeShareRequestObject) (ConsumeShareResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(w http.ResponseWriter, r *http.Request) {
	var request GetReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateShare operation middleware
func (sh *strictHandler) CreateShare(w http.ResponseWriter, r *http.Request) {
	var request CreateShareRequestObject

	var body CreateShareJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateShare(ctx, request.(CreateShareRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateShare")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateShareResponseObject); ok {
		if err := validResponse.VisitCreateShareResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeShare operation middleware
func (sh *strictHandler) RevokeShare(w http.ResponseWriter, r *http.Request, share openapi_types.UUID) {
	var request RevokeShareRequestObject

	request.Share = share

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeShare(ctx, request.(RevokeShareRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeShare")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeShareResponseObject); ok {
		if err := validResponse.VisitRevokeShareResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConsumeShare operation middleware
func (sh *strictHandler) ConsumeShare(w http.ResponseWriter, r *http.Request, share ShareCapability) {
	var request ConsumeShareRequestObject

	request.Share = share

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConsumeShare(ctx, request.(ConsumeShareRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConsumeShare")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConsumeShareResponseObject); ok {
		if err := validResponse.VisitConsumeShareResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
